name: release

on:
  push:
    branches:
      - master
    paths:
      - 'version.txt'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from history
        id: get_version
        run: |
          # get hash and version number
          SHORT_HASH=$(git rev-parse --short HEAD)
          VERSION=$(git log --pretty=format:"%s" -1 | grep -oP "\d+\.\d+(\.\d+)?" || true)

          # set output
          echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT
          if [ -z "$VERSION" ]; then
            echo "Version not found, skipping release creation."
            echo "version=latest" >> $GITHUB_OUTPUT
          else
            echo "Found version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Zip extension files
        run: |
          # whitelist copy
          mkdir release-build
          cp -r ./_locales ./release-build/
          cp -r ./css ./release-build/
          cp -r ./icon ./release-build/
          cp -r ./page ./release-build/
          cp -r ./scripts ./release-build/
          cp background.js ./release-build/
          cp image-viewer.js ./release-build/
          cp license ./release-build/
          cp manifest.json ./release-build/
          cp readme.md ./release-build/
          cp version.txt ./release-build/

          # zip files
          cd release-build
          zip -r "../image-viewer-v${{ steps.get_version.outputs.version }}.zip" .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_version.outputs.version }}-${{ steps.get_version.outputs.short_hash }}
          path: image-viewer-v${{ steps.get_version.outputs.version }}.zip
          retention-days: 5

      - name: Create release
        if: ${{ steps.get_version.outputs.version != 'latest' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: v${{ steps.get_version.outputs.version }}
          files: image-viewer-v${{ steps.get_version.outputs.version }}.zip
          draft: true
          prerelease: false
          body: |
            Version: ${{ steps.get_version.outputs.version }}
            Commit hash: ${{ steps.get_version.outputs.short_hash }}
            Automated build and release.
